default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: baljinder
  password: Gurdeep@11
  host: 127.0.0.1

development:
  <<: *default
  database: ecommerce_rails

test:
  <<: *default
  database: ecommerce_railstesting

production:
  <<: *default
  database: ecommerce_railsprod
  username: postgres
  password: 20101600
  url: <%= ENV["DATABASE_URL"] %>